services:
  - type: web
    name: messenger-bot
    env: python
    branch: main
    buildCommand: ""
    startCommand: python webhook.py
    plan: free
    envVars:
      - key: PORT
        value: 10000

